[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (1): 127.0.0.1
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:396 http://127.0.0.1:5000 "GET /list_users_id HTTP/1.1" 200 188
[35mDEBUG   [0m root:helpers_func.py:8 Response status is 200
[35mDEBUG   [0m root:helpers_func.py:39 Request completed in 7.845 ms
[35mDEBUG   [0m root:helpers_func.py:45 Getting response body from API
[32mINFO    [0m root:helpers_func.py:52 Check type 0<class 'dict'>